version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=doadmin
      - MONGO_INITDB_ROOT_PASSWORD=HearthGate2024!

  backend:
    build: ./backend
    container_name: hearthgate-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://doadmin:HearthGate2024!@mongodb:27017/admin?authSource=admin
      - JWT_SECRET=hearthgate-secret-key-2025

  frontend:
    build: ./frontend
    container_name: hearthgate-frontend
    restart: always
    ports:
      - "3000:80"  # Changed from 80:80 to 3000:80
    depends_on:
      - backend
